#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /bin/sh -c "cd /opt/kiezbox-messages; /opt/kiezbox-messages/venv/bin/uvicorn main:app --reload --port 80 --host 0.0.0.0"
        procd_set_param env PWD=/opt/kiezbox-messages
        procd_set_param pidfile /var/run/kb-app.pid
        procd_set_param respawn 150 10 10
        procd_set_param stderr 1
        procd_close_instance
}
