#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /bin/sh -c "cd /root/ && /usr/bin/cmd -settime=true -dbwriter=true -dbretry=true"
        procd_set_param env PWD=/root/
        procd_set_param pidfile /var/run/kb-gateway.pid
        procd_set_param respawn 150 10 10
        procd_set_param stderr 1
        procd_close_instance
}
